GS_ITEM-AMOUNT = GS_ITEM-MENGE * GS_ITEM-NETPR.

IF GS_ITEM-WAERS = 'VND'.
  GS_ITEM-AMOUNT = GS_ITEM-AMOUNT * 100.
ENDIF.

" 1. Tính toán giá trị gốc
**GS_ITEM-AMOUNT = GS_ITEM-MENGE * GS_ITEM-NETPR.
**
**IF GS_ITEM-WAERS = 'VND'.
**   GS_ITEM-AMOUNT = GS_ITEM-AMOUNT * 100.
**ENDIF.
**
**GD_TOTAL = GD_TOTAL + GS_ITEM-AMOUNT.

" 1. Tính tiền từng dòng vào LINE_TOTAL (Trường Bear mới tạo)
GS_ITEM-LINE_TOTAL = GS_ITEM-MENGE * GS_ITEM-NETPR.

*" 2. Nhân 100 cho VND để hiển thị đúng
*IF GS_ITEM-WAERS = 'VND'.
*  GS_ITEM-LINE_TOTAL = GS_ITEM-LINE_TOTAL * 100.
*ENDIF.
*
*" 3. Cộng dồn vào trường AMOUNT của biến Global GD_TOTAL
*GD_TOTAL-AMOUNT = GD_TOTAL-AMOUNT + GS_ITEM-LINE_TOTAL.
